### ISSUE TITLE
Crash, no run

### ISSUE THREAD

**Issue by Makein** [uyjulian/renpy-switch#1]
Help?
1) "C:\nacptool --create Game RenPy 1.3.1 C:\Game.ncap"
2) "C:\elf2nro renpy-switch.elf game.nro --icon=C:\game.ico --ncap=C:\Game.ncap --romfsdir=C:\Romfs\" 
Inside 
C:\Romfs\Contents\game\
C:\Romfs\Contents\lib\
C:\Romfs\Contents\renpy\
C:\Romfs\Contents\renpy.py

Nro file no have author and icon in homebrew viewer and don't run-work.
Step by step instruction would be nice

**Comment by uyjulian** [comment]
Icon needs to be 256x256 JPEG format. The Author argument should be "RenPy". What does "don't run-work" mean?

**Comment by Makein** [comment]
> 
> 
> Icon needs to be 256x256 JPEG format. The Author argument should be "RenPy". Explain "don't run-work."

I run it in homebrew launcher, then wait and it go back to homebrew launcher.
If you run again console reboot...
I done all right?
Here are sample: https://cloud.mail.ru/public/47NG/3xiqY4Vpz

**Comment by uyjulian** [comment]
Katawa Shoujo won't work as-is on Ren'Py 7.3.0, which this port is based off.
