### ISSUE TITLE
It does not keep aspect ratio correctly in case of 4:3 ratio

### ISSUE THREAD

**Issue by perillamint** [uyjulian/renpy-switch#10]
Hello, I tried your Ren'Py port and successfully ported Kindred Spirits on the Roof to Switch. The problem is, it uses 800 x 600 resolution and Ren'Py switch displays it "stretched" horizontally. (does not keep aspect ratio)

It seems there is a problem exist in the resolution configuration routine or so. By guessing from switching fullscreen/windowed mode while docked fixes this problem temporary, I personally suspect gl2/gl2draw.pyx:353, which does not handle Nintendo Switch's case but I didn't experimented with it yet.

**Comment by uyjulian** [comment]
switch-sdl2 recently added a feature where it will automatically change the resolution when the console is docked and undocked. However, the code does not execute until the console is docked or undocked.  
I'll see if I can fix this issue.
