### ISSUE TITLE
_socket module not in the release

### ISSUE THREAD

**Issue by jexom** [uyjulian/renpy-switch#11]
Despite the release notes for 1.7 say that the _socket module was added I get the error depicted in the screenshot while launching the game
![2020052416261200-96ACD4E6FB5B8490CB5D854040BA0674](https://user-images.githubusercontent.com/6067696/82755345-8a2fab80-9ddb-11ea-99e8-be3b7ca6e330.jpg)

**Comment by uyjulian** [comment]
I made a mistake by using outdated libraries.
This will be fixed in the next release.

**Comment by uyjulian** [comment]
This was fixed: https://github.com/uyjulian/renpy-switch/releases/tag/v1.7.1
