### ISSUE TITLE
Nro Forwarders blocked by this

### ISSUE THREAD

**Issue by fennectech** [uyjulian/renpy-switch#13]
This prevents NRO forwarders or an HBMENU nro from working

**Comment by uyjulian** [comment]
Please describe the issue in more detail.

**Comment by fennectech** [comment]
using an hbmenu NSP forwarder i get blocked by your "this only works with title takeover" error

**Comment by uyjulian** [comment]
Due to the memory requirements, the program will only start when using Application takeover instead of Applet takeover. The program will check for this by ensuring that `__nx_applet_type` is set to `AppletType_Application`. Are you sure you are using Application takeover?

**Comment by fennectech** [comment]
No  im using an Homebrew NSP to launch it

**Comment by uyjulian** [comment]
Are you holding the "R" button while launching the application?

**Comment by uyjulian** [comment]
This is an issue with the forwarder not setting the environment correctly. This is not my issue.

You may want to open an issue with the forwarder specifying that `__nx_applet_type` is not set to `AppletType_Application` which results in the check failing.
