### ISSUE TITLE
Files placed in romfs ignored

### ISSUE THREAD

**Issue by ObscenityIB** [uyjulian/renpy-switch#17]
The readme says 

> The following files or folders are required to be in the same directory as the .nro **or** in RomFS:

But placing lib.zip in romfs/Contents is ignored, displaying an error that lib.zip was not found

**Comment by uyjulian** [comment]
Looks like some behavior has changed. I'll take a closer look…

**Comment by uyjulian** [comment]
I have tested it myself, and it works. Check the file hierarchy with nstool.

**Comment by n1spro** [comment]
also writes that lib.zip was not found

**Comment by n1spro** [comment]
with some games there is a problem, not with seven

**Comment by n1spro** [comment]
> I have tested it myself, and it works. Check the file hierarchy with nstool.

with some games there is a problem, not with seven
